services:

  # Weapp container 
  piststop-webapp:
    image: pitstop-webapp
    container_name: piststop-webapp
    restart: always
    networks:
      - pitstopNetwork


  # Gateway container 
  pitstop-express-gateway:
    image: pitstop-express-gateway
    container_name: pitstop-express-gateway
    restart: always
    ports:
      - 8080:8080
    networks:
      - pitstopNetwork

  # Pitsotp-Customer contaier 
  pitstop-customer-service:
    image: pitstop-customer
    container_name: pitstop-customer-service
    restart: always
    networks:
      - pitstopNetwork
    environment:
      DB_USER: customer
      DB_PASSWORD: password
      DB_NAME: customer
      DB_HOST: customer-database
      MESSAGE_BUS_USERNAME: admin
      MESSAGE_BUS_PASSWORD: password
      MESSAGE_BUS: rabbitmq  
      MESSAGE_BUS_TIMEOUT: 5000
      PORT: 3001
  
  # Pitstop-Customer Database       
  customer-database:
    image: mysql
    container_name: customer-database
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: customer
      MYSQL_USER: customer
      MYSQL_PASSWORD: password
    volumes:
      - customer-database:/var/lib/mysql
    networks:
      - pitstopNetwork
        



  # Pitstop-Vehicle container 
  pitstop-vehicle-service:
    image: pitstop-vehicle
    container_name: pitstop-vehicle-service
    restart: always
    networks:
      - pitstopNetwork
    environment:
      DB_USER: vehicle
      DB_PASSWORD: password
      DB_NAME: vehicle
      DB_HOST: vehicle-database
      MESSAGE_BUS_USERNAME: admin
      MESSAGE_BUS_PASSWORD: password
      MESSAGE_BUS: rabbitmq
      MESSAGE_BUS_TIMEOUT: 500
      PORT: 3002

  # Pitstop-Vehicle Database
  vehicle-database:
    image: mysql
    container_name: vehicle-database
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: vehicle
      MYSQL_USER: vehicle
      MYSQL_PASSWORD: password
    volumes:
      - vehicle-database:/var/lib/mysql
    networks:
      - pitstopNetwork



  # Pistop-Workshop container 
  pitstop-workshop-service:
    image: pitstop-workshop-planning
    container_name: pitstop-workshop-service
    restart: always
    networks:
      - pitstopNetwork
    environment:
      DB_USER: workshop
      DB_PASSWORD: password
      DB_NAME: workshop
      DB_HOST: workshop-database
      MESSAGE_BUS_USERNAME: admin
      MESSAGE_BUS_PASSWORD: password
      MESSAGE_BUS: rabbitmq
      MESSAGE_BUS_TIMEOUT: 5000
      PORT: 3003

  # Pitstop-Workshop Database      
  workshop-database:
    image: mysql
    container_name: workshop-databas
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: workshop
      MYSQL_USER: workshop
      MYSQL_PASSWORD: password
    volumes:
      - workshop-database:/var/lib/mysql
    networks:
      - pitstopNetwork

  # RabbitMQ container
  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    restart: always
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=password
    networks:
      - pitstopNetwork
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
      - rabbitmq-data:/var/log/rabbitmq

volumes:
  customer-database:
  vehicle-database:
  workshop-database:
  rabbitmq-data:

networks:
  pitstopNetwork:
    driver: bridge
