name: Build Docker Images for Changed Services
on:
  push:
    branches:
      - main
    paths:
      - 'pitstop-express-gateway/**'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build pitstop-express-gateway Docker image
      run: cd pitstop-express-gateway && docker build -t pitstop-express-gateway:latest .
    - name: Login to Docker Hub
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: echo "${DOCKER_PASSWORD}" | docker login -u "${DOCKER_USERNAME}" --password-stdin

    - name: Push Docker image to Docker Hub
      run: docker tag pitstop-express-gateway:latest simohassane/pitstop-express-gateway:latest && docker push simohassane/pitstop-express-gateway:latest
