name: Build Docker Images

on:
  push:
    branches:
      - main
      - 'refs/tags/*' # Optional: to build on tags
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Get changed services
        id: changed_services
        run: |
          # Get the list of changed directories
          changed_services=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep '^service' | awk 'BEGIN {FS="/"} {print $1}' | sort -u)
          echo "changed_services=$changed_services" >> $GITHUB_ENV

      - name: Build Docker images
        if: env.changed_services != ''
        run: |
          IFS=',' read -ra services <<< "$changed_services"
          for service in "${services[@]}"; do
            echo "Building $service"
            docker build -t myregistry/$service:latest ./$service
            # Optionally push the image
            # docker push myregistry/$service:latest
          done
